### PR TITLE
Fix name size from edit Label (in backend and frontend).

### PR DESCRIPTION
**Pull request by CherifAmine**
## **Description**

Fix name size from edit Label

## **Related Issue(s)**
https://github.com/riadvice/bbbeasy/issues/617

## **Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Automated testing implementation or update
- [ ] Dependencies updated to a newer version
- [ ] Documentation update
- [ ] Experimental feature that requires further discussion

## **Screenshots and screen captures**
image

### CODE REVIEW

**Comment by GhaziTriki** [comment]
Indeed error display in BBBeasy forms are global and rarely contextual by choice. @marwa-benhassine Can you tell us why QA is requesting changes?

**Comment by marwa-benhassine** [comment]
@CherifAmine 

image

The validation error message should be global and displayed above the form like the validation message in installer 

like this one :

image

**Comment by marwa-benhassine** [comment]
when we keep the label name without changes the validation error message should not remain static but rather disappear .

label name cannot

**Comment by CherifAmine** [comment]
Fix in PR : https://github.com/riadvice/bbbeasy/pull/855

**Pull request closed without merging**
