### PR TITLE
Clear data when the close button is clicked

### PR DESCRIPTION
**Pull request by CherifAmine**
## **Related Issue(s)**
https://github.com/riadvice/bbbeasy/issues/860

## **Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Automated testing implementation or update
- [ ] Dependencies updated to a newer version
- [ ] Documentation update
- [ ] Experimental feature that requires further discussion

### CODE REVIEW

**Comment by marwa-benhassine** [comment]
When you click the close icon button on the new label, the color is not cleared
the color should return to the default value 

color

**Comment by marwa-benhassine** [comment]
the shortlink  should return to the default value
shortlink

**Comment by marwa-benhassine** [comment]
the edit box in a short link stays open when the close button is clicked

**Comment by CherifAmine** [comment]
Replaced by PR : https://github.com/riadvice/bbbeasy/pull/886

**Pull request closed without merging**
