### PR TITLE
Fix name size from edit Label (in backend and frontend)

### PR DESCRIPTION
**Pull request by CherifAmine**
## **Description**

Fix name size from edit Label

## **Related Issue(s)**
https://github.com/riadvice/bbbeasy/issues/617

## **Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Automated testing implementation or update
- [ ] Dependencies updated to a newer version
- [ ] Documentation update
- [ ] Experimental feature that requires further discussion

## **Screenshots and screen captures**
image

image

image

### CODE REVIEW

**Comment by marwa-benhassine** [comment]
the height is too long when using labels.
image

**Comment by marwa-benhassine** [comment]
the label is  outside  of the room details  box 
image

**Comment by GhaziTriki** [comment]
The solution is to truncate on display and tooltip on hover for complete display.

**Comment by CherifAmine** [comment]
Replaced by PR : https://github.com/riadvice/bbbeasy/pull/893

**Pull request closed without merging**
